# SPDX-FileCopyrightText: 2022 Christian Mee√üen (GFZ) <christian.meessen@gfz-potsdam.de>
# SPDX-FileCopyrightText: 2022 Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences
# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
#
# SPDX-License-Identifier: Apache-2.0

name: build latest images

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - "published"

jobs:

  auth:
    name: auth
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/hifis-net/rsd-saas/auth
      image_tag: ${{ startsWith(github.ref, 'refs/tags/hifis-') && github.ref_name || github.sha }}
      dockerfile: authentication/Dockerfile
      docker_context: ./authentication
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  database:
    name: database
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/hifis-net/rsd-saas/database
      image_tag: ${{ startsWith(github.ref, 'refs/tags/hifis-') && github.ref_name || github.sha }}
      dockerfile: database/Dockerfile
      docker_context: ./database
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  backend:
    name: backend api
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/hifis-net/rsd-saas/backend
      image_tag: ${{ startsWith(github.ref, 'refs/tags/hifis-') && github.ref_name || github.sha }}
      dockerfile: backend-postgrest/Dockerfile
      docker_context: ./backend-postgrest
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  frontend:
    name: frontend
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/hifis-net/rsd-saas/frontend
      image_tag: ${{ startsWith(github.ref, 'refs/tags/hifis-') && github.ref_name || github.sha }}
      dockerfile: frontend/Dockerfile
      docker_context: ./frontend
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  nginx:
    name: nginx
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/hifis-net/rsd-saas/nginx
      image_tag: ${{ startsWith(github.ref, 'refs/tags/hifis-') && github.ref_name || github.sha }}
      dockerfile: nginx/Dockerfile
      docker_context: ./nginx
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  scrapers:
    name: scrapers
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/hifis-net/rsd-saas/scrapers
      image_tag: ${{ startsWith(github.ref, 'refs/tags/hifis-') && github.ref_name || github.sha }}
      dockerfile: scrapers/Dockerfile
      docker_context: ./scrapers
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
